# Generated by Django 2.1.8 on 2019-04-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_created_sub_category_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
