# Generated by Django 2.1.8 on 2019-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_categories_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='static/source/image'),
            preserve_default=False,
        ),
    ]
