# Generated by Django 2.1.8 on 2019-04-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_create_table_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsproductuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used', to=settings.AUTH_USER_MODEL),
        ),
    ]
